### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by alichtman** [k0pernicus/goyave#1]
Hey there,

This looks cool, and I wanted to try it out!

I tried installing and got this error message:

![image](https://user-images.githubusercontent.com/20600565/42139249-3bf47bb2-7d58-11e8-943f-b40e7344367b.png)

Is this an issue on your end or mine?

**Comment by k0pernicus** [comment]
Hello!
Hum, that's weird...
It seems `get` does not reach github.com 🤔 

Can you try with `go get -v github.com/k0pernicus/goyave` please?
Also, please to use `libgit2` and `git2go` v26  :)

**Comment by alichtman** [comment]
![image](https://user-images.githubusercontent.com/20600565/42190418-fa1acc18-7e2a-11e8-8baf-21e902e4f65c.png)

It doesn't look like something is configured correctly with my go install (maybe?)

**Comment by k0pernicus** [comment]
Usually, the `cannot find package` error happens when `GOPATH` is not set (but it seems like `GOPATH` is already set for you).
Can you give me your version of `go` please?
Currently, my version of `go` is go1.10.3 (darwin/amd64).

Maybe you can check your installation importing another go project.
Can you try `go get -v -u github.com/golang/example/hello` please?

**Comment by alichtman** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/20600565/42199681-d02cfdee-7e5d-11e8-85da-04ca9257716e.png">

Reinstalled go and tested the installation too.

No luck.

**Comment by k0pernicus** [comment]
Ok, I see.
Did you tried to set `GOPATH` to `$HOME/go`?

```
# in .zshrc, or .zprofile
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
```

and `source ~/.zshrc`

**Comment by alichtman** [comment]
I have those set. Still no luck.

**Comment by k0pernicus** [comment]
Hi @alichtman 
Do you still have any troubles in installing goyave?

**Comment by alichtman** [comment]
I'm having trouble installing any go packages. I gave up for the moment, but I'll find some time to mess with it later in the year. It's probably safe to say the issue is on my end...
